version: "3.3"
services:
  terraform:
    build:
      context: ./deployment
      dockerfile: Dockerfile
    working_dir: /usr/local/src
    entrypoint: bash
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - DB_DEBUG=1
      - IMAGE_VERSION=${IMAGE_VERSION:-latest}
      - DB_STATE=${DB_STATE:-pa}
      - DB_SETTINGS_BUCKET=${DB_SETTINGS_BUCKET:-districtbuilder-staging-config-us-east-1}
      - DOCKER_HOST=${DOCKER_HOST:-origin.staging.pa.districtbuilder.azavea.com:2476}
    volumes:
      - ./:/usr/local/src
      - ~/.ssh:/root/.ssh
