version: "3.3"
services:
  nginx:
    image: quay.io/azavea/districtbuilder-nginx:${GIT_COMMIT}
  django:
    image: quay.io/azavea/districtbuilder-app:${GIT_COMMIT}
  geoserver:
    image: quay.io/azavea/districtbuilder-geoserver:${GIT_COMMIT}
  terraform:
    image: quay.io/azavea/terraform:0.10.8
    volumes:
      - ./:/usr/local/src
      - ~/.ssh:/root/.ssh
