version: "3.3"
services:
  terraform:
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_PROFILE=${AWS_PROFILE:-district-builder}
    volumes:
      - ~/.aws:/root/.aws
