# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redistricting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characteristic',
            unique_together=set([('subject', 'geounit')]),
        ),
    ]
