# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-06 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('redistricting', '0002_auto_20180125_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('team_member_names', models.CharField(blank=True, max_length=500)),
                ('team_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=14)),
                ('county', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=5)),
                ('contest_division', models.CharField(choices=[(b'ADULT', b'Adult (non-student)'), (b'YOUTH', b'Youth (grades 5-12)'), (b'ACADM', b'Higher Ed (Undergraduate, graduate, professional')], max_length=5)),
                ('values_statement', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redistricting.Plan')),
                ('submitting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
