# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redistricting', '0003_plansubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubmission',
            name='submitted_plan_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
