# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-27 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redistricting', '0004_plansubmission_submitted_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubmission',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
