#!/bin/bash
set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

if [[ -n "${TRAVIS_COMMIT}" ]]; then
    GIT_COMMIT="${TRAVIS_COMMIT:0:7}"  
else
    GIT_COMMIT=$(git rev-parse --short HEAD)
fi

DIR="$(dirname "${0}")"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Build container images and run tests.
"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else

    # Run Tests
    "${DIR}/../scripts/test"

    # Build container images
    GIT_COMMIT="${GIT_COMMIT}" docker-compose \
        -f docker-compose.yml \
        -f docker-compose.ci.yml build \
        nginx django geoserver
    fi
    exit
fi
