#!/bin/bash
set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "${0}")"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Publish containers and run deployments.
"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else

    # Publish containers
    "${DIR}/cipublish"

    fi
    exit
fi
