#!/bin/bash
set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

function usage() {

    echo -n \
"Usage: $(basename "$0")

Load a database dump from S3
"
}

function load_dev_data() {
    echo "Creating directory to download data into in django container"
    docker-compose \
        exec -T django mkdir -p /data

    echo "Downloading shapefile"
    docker-compose \
        exec -T django \
        wget -q \
            -O /data/VA_data.zip \
            https://s3.amazonaws.com/districtbuilderdata/VA_data.zip

    echo "Unzipping shapefile"
    docker-compose \
        exec -T django \
        unzip -o /data/VA_data.zip -d /data

    echo "Drop district_builder database"
    docker-compose \
        exec -T postgres gosu postgres dropdb district_builder

    echo "Create district_builder database"
    docker-compose \
        exec -T postgres gosu postgres createdb district_builder

    echo "Running migrations"
    docker-compose \
        exec -T django ./manage.py migrate

    echo "Loading shapefiles into database"
    docker-compose \
        exec -T django ./manage.py setup config/config.xml -g0 -g1 -g2

    echo "Nesting geolevels"
    docker-compose \
        exec -T django ./manage.py setup config/config.xml -n0 -n1 -n2

    echo "Creating template plans"
    docker-compose \
        exec -T django ./manage.py setup config/config.xml -t

    echo "Creating database views"
    docker-compose \
        exec -T django ./manage.py setup config/config.xml --views

    echo "Configuring geoserver"
    docker-compose \
        exec -T django ./manage.py setup config/config.xml -G

}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose up -d postgres django
        load_dev_data
    fi
    exit
fi
