#!/bin/bash
set -eu

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0") [--with-airflow]

Starts servers using docker-compose
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose up --remove-orphans
    fi
    exit
fi