#!/bin/bash
set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

GIT_COMMIT="${GIT_COMMIT:-latest}"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Run various test suites.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        if which shellcheck &>/dev/null; then
            echo "Linting STRTA scripts"
            find ./scripts -type f -print0 | xargs -0 -r shellcheck
        fi
    fi
    exit
fi
