#!/bin/bash
set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

function usage() {

    echo -n \
"Usage: $(basename "$0")
Setup external project dependencies.
"
}


function build_containers() {
    docker-compose build
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        echo "Building containers"
        build_containers
    fi
    exit
fi
