- hosts: app-server
  become: True

  # Add pip packages to root user PATH
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

  pre_tasks:
    - name: Update Yum cache
      command: yum update -y

  roles:
    - { role: "azavea.python-security" }
    - { role: "district-builder.app-server"}
